### ISSUE TITLE
NER无法复现代码

### ISSUE THREAD

**Issue by qianxliu** [rsanshierli/EasyBert#7]
@rsanshierli 
预测输出如下
```bash
[Predicting] 10/10 [==============================] 16.0ms/step{'text': '四川敦煌学”。近年来，丹棱县等地一些不知名的石窟迎来了海内外的游客，他们随身携带着胡文和的著作。', 'label': {'movie': {'四': [[0, 0]]}, 'game': {'学': [[4, 4]]}, 'company': {'。': [[6, 6], [47, 47]], '年': [[8, 8]], '来': [[9, 9]], '，': [[10, 10], [33, 33]], '丹': [[11, 11]], '县': [[13, 13]], '地': [[15, 15]], '些': [[17, 17]], '名': [[20, 20]], '的': [[21, 21], [30, 30], [44, 44]], '了': [[26, 26]], '外': [[29, 29]], '客': [[32, 32]], '们': [[35, 35]], '身': [[37, 37]], '着': [[40, 40]]}, 'name': {'棱': [[12, 12]], '等': [[14, 14]], '他': [[34, 34]]}, 'government': {'知': [[19, 19]], '窟': [[23, 23]], '迎': [[24, 24]], '海': [[27, 27]], '著': [[45, 45]]}}}
{'text': '尼日利亚海军发言人当天在阿布贾向尼日利亚通讯社证实了这一消息。', 'label': {'position': {'军': [[5, 5]]}, 'government': {'发': [[6, 6]], '阿': [[12, 12]], '贾': [[14, 14]], '利': [[18, 18]], '亚': [[19, 19]], '通': [[20, 20]], '证': [[23, 23]], '息': [[29, 29]]}, 'company': {'当': [[9, 9]], '天': [[10, 10]], '向': [[15, 15]], '了': [[25, 25]]}}}
{'text': '销售冠军：辐射3-Bethesda', 'label': {'company': {'销': [[0, 0]], 'B': [[9, 9]], 'e': [[10, 10]], 'a': [[16, 16]]}, 'scene': {'售': [[1, 1]], '：': [[4, 4]], 't': [[11, 11]], 'e': [[13, 13]], 's': [[14, 14]]}, 'address': {'军': [[3, 3]]}, 'position': {'h': [[12, 12]]}}}
{'text': '所以大多数人都是从巴厘岛南部开始环岛之旅。', 'label': {'name': {'大': [[2, 2]], '从': [[8, 8]], '厘': [[10, 10]], '部': [[13, 13]]}, 'company': {'数': [[4, 4]], '人': [[5, 5]], '都': [[6, 6]], '是': [[7, 7]], '巴': [[9, 9]], '之': [[18, 18]], '旅': [[19, 19]]}}}
{'text': '备受瞩目的动作及冒险类大作《迷失》在其英文版上市之初就受到了全球玩家的大力追捧。', 'label': {'company': {'备': [[0, 0]], '受': [[1, 1]], '之': [[24, 24]], '初': [[25, 25]], '了': [[29, 29]], '家': [[33, 33]], '力': [[36, 36]], '捧': [[38, 38]]}, 'scene': {'瞩': [[2, 2]]}, 'government': {'险': [[9, 9]], '类': [[10, 10]]}, 'name': {'在': [[17, 17]], '大': [[35, 35]]}}}
{'text': 'filippagowski：14岁时我感觉自己像梵高', 'label': {'movie': {'f': [[0, 0]]}, 'company': {'i': [[12, 12]]}, 'government': {'像': [[23, 23]], '梵': [[24, 24]]}}}
{'text': '央视新址文化中心外立面受损严重', 'label': {'company': {'央': [[0, 0]], '新': [[2, 2]], '化': [[5, 5]], '重': [[14, 14]]}, 'name': {'视': [[1, 1]]}, 'government': {'中': [[6, 6]], '心': [[7, 7]]}}}
{'text': '单看这张彩票，税前总奖金为5063992元。本张票面缩水后阿森纳的结果全部为0，斯图加特全部为1，', 'label': {'name': {'看': [[1, 1]], '6': [[15, 15]]}, 'company': {'这': [[2, 2]], '票': [[5, 5], [24, 24]], '前': [[8, 8]], '金': [[11, 11]], '本': [[22, 22]], '面': [[25, 25]], '缩': [[26, 26]]}, 'government': {'彩': [[4, 4]], '奖': [[10, 10]], '水': [[27, 27]], '阿': [[29, 29]], '森': [[30, 30]], '纳': [[31, 31]], '果': [[34, 34]], '0': [[38, 38]], '斯': [[40, 40]], '图': [[41, 41]], '加': [[42, 42]], '特': [[43, 43]], '为': [[46, 46]]}, 'scene': {'为': [[12, 12]], '9': [[18, 18]], '2': [[19, 19]]}, 'game': {'1，': [[47, 48]]}}}
{'text': '你会和星级厨师一道先从巴塞罗那市中心兰布拉大道的laboqueria市场的开始挑选食材，', 'label': {'name': {'你': [[0, 0]], '级': [[4, 4]], '先': [[9, 9]], '从': [[10, 10]], '中': [[16, 16]], '心': [[17, 17]], '布': [[19, 19]]}, 'company': {'和': [[2, 2]]}, 'position': {'巴': [[11, 11]]}, 'scene': {'塞': [[12, 12]]}, 'government': {'大': [[21, 21]], '道': [[22, 22]], '市': [[34, 34]], '材': [[42, 42]]}}}
{'text': '波特与凤凰社》的率队下更加红火。乘着7月的上升气流，《发胶》、《辛普森一家》、《谍影憧憧ⅲ》', 'label': {'name': {'特': [[1, 1]]}, 'scene': {'凰': [[4, 4]], '》': [[6, 6], [45, 45]], '乘': [[16, 16]], '月': [[19, 19]], '升': [[22, 22]], '发': [[27, 27]], '影': [[41, 41]]}, 'company': {'的': [[7, 7]], '。': [[15, 15]], '流': [[24, 24]]}, 'government': {'率': [[8, 8]], '队': [[9, 9]], '加': [[12, 12]], '》': [[29, 29], [37, 37]], '辛': [[32, 32]], '普': [[33, 33]], '森': [[34, 34]], '家': [[36, 36]]}}}
```
试了好几次都是这样
已经尝试过Albert, Roberta等

**Comment by RX-00-Cat** [comment]
你好，我跑的时候出现了以下错误：
 Model name './NER/outputs/cluener_output/bert' was not found in tokenizers model name list 
想请教一下，当时您是如何跑起来的，非常感激

**Comment by RX-00-Cat** [comment]
> @rsanshierli 预测输出如下
> 
> ```shell
> [Predicting] 10/10 [==============================] 16.0ms/step{'text': '四川敦煌学”。近年来，丹棱县等地一些不知名的石窟迎来了海内外的游客，他们随身携带着胡文和的著作。', 'label': {'movie': {'四': [[0, 0]]}, 'game': {'学': [[4, 4]]}, 'company': {'。': [[6, 6], [47, 47]], '年': [[8, 8]], '来': [[9, 9]], '，': [[10, 10], [33, 33]], '丹': [[11, 11]], '县': [[13, 13]], '地': [[15, 15]], '些': [[17, 17]], '名': [[20, 20]], '的': [[21, 21], [30, 30], [44, 44]], '了': [[26, 26]], '外': [[29, 29]], '客': [[32, 32]], '们': [[35, 35]], '身': [[37, 37]], '着': [[40, 40]]}, 'name': {'棱': [[12, 12]], '等': [[14, 14]], '他': [[34, 34]]}, 'government': {'知': [[19, 19]], '窟': [[23, 23]], '迎': [[24, 24]], '海': [[27, 27]], '著': [[45, 45]]}}}
> {'text': '尼日利亚海军发言人当天在阿布贾向尼日利亚通讯社证实了这一消息。', 'label': {'position': {'军': [[5, 5]]}, 'government': {'发': [[6, 6]], '阿': [[12, 12]], '贾': [[14, 14]], '利': [[18, 18]], '亚': [[19, 19]], '通': [[20, 20]], '证': [[23, 23]], '息': [[29, 29]]}, 'company': {'当': [[9, 9]], '天': [[10, 10]], '向': [[15, 15]], '了': [[25, 25]]}}}
> {'text': '销售冠军：辐射3-Bethesda', 'label': {'company': {'销': [[0, 0]], 'B': [[9, 9]], 'e': [[10, 10]], 'a': [[16, 16]]}, 'scene': {'售': [[1, 1]], '：': [[4, 4]], 't': [[11, 11]], 'e': [[13, 13]], 's': [[14, 14]]}, 'address': {'军': [[3, 3]]}, 'position': {'h': [[12, 12]]}}}
> {'text': '所以大多数人都是从巴厘岛南部开始环岛之旅。', 'label': {'name': {'大': [[2, 2]], '从': [[8, 8]], '厘': [[10, 10]], '部': [[13, 13]]}, 'company': {'数': [[4, 4]], '人': [[5, 5]], '都': [[6, 6]], '是': [[7, 7]], '巴': [[9, 9]], '之': [[18, 18]], '旅': [[19, 19]]}}}
> {'text': '备受瞩目的动作及冒险类大作《迷失》在其英文版上市之初就受到了全球玩家的大力追捧。', 'label': {'company': {'备': [[0, 0]], '受': [[1, 1]], '之': [[24, 24]], '初': [[25, 25]], '了': [[29, 29]], '家': [[33, 33]], '力': [[36, 36]], '捧': [[38, 38]]}, 'scene': {'瞩': [[2, 2]]}, 'government': {'险': [[9, 9]], '类': [[10, 10]]}, 'name': {'在': [[17, 17]], '大': [[35, 35]]}}}
> {'text': 'filippagowski：14岁时我感觉自己像梵高', 'label': {'movie': {'f': [[0, 0]]}, 'company': {'i': [[12, 12]]}, 'government': {'像': [[23, 23]], '梵': [[24, 24]]}}}
> {'text': '央视新址文化中心外立面受损严重', 'label': {'company': {'央': [[0, 0]], '新': [[2, 2]], '化': [[5, 5]], '重': [[14, 14]]}, 'name': {'视': [[1, 1]]}, 'government': {'中': [[6, 6]], '心': [[7, 7]]}}}
> {'text': '单看这张彩票，税前总奖金为5063992元。本张票面缩水后阿森纳的结果全部为0，斯图加特全部为1，', 'label': {'name': {'看': [[1, 1]], '6': [[15, 15]]}, 'company': {'这': [[2, 2]], '票': [[5, 5], [24, 24]], '前': [[8, 8]], '金': [[11, 11]], '本': [[22, 22]], '面': [[25, 25]], '缩': [[26, 26]]}, 'government': {'彩': [[4, 4]], '奖': [[10, 10]], '水': [[27, 27]], '阿': [[29, 29]], '森': [[30, 30]], '纳': [[31, 31]], '果': [[34, 34]], '0': [[38, 38]], '斯': [[40, 40]], '图': [[41, 41]], '加': [[42, 42]], '特': [[43, 43]], '为': [[46, 46]]}, 'scene': {'为': [[12, 12]], '9': [[18, 18]], '2': [[19, 19]]}, 'game': {'1，': [[47, 48]]}}}
> {'text': '你会和星级厨师一道先从巴塞罗那市中心兰布拉大道的laboqueria市场的开始挑选食材，', 'label': {'name': {'你': [[0, 0]], '级': [[4, 4]], '先': [[9, 9]], '从': [[10, 10]], '中': [[16, 16]], '心': [[17, 17]], '布': [[19, 19]]}, 'company': {'和': [[2, 2]]}, 'position': {'巴': [[11, 11]]}, 'scene': {'塞': [[12, 12]]}, 'government': {'大': [[21, 21]], '道': [[22, 22]], '市': [[34, 34]], '材': [[42, 42]]}}}
> {'text': '波特与凤凰社》的率队下更加红火。乘着7月的上升气流，《发胶》、《辛普森一家》、《谍影憧憧ⅲ》', 'label': {'name': {'特': [[1, 1]]}, 'scene': {'凰': [[4, 4]], '》': [[6, 6], [45, 45]], '乘': [[16, 16]], '月': [[19, 19]], '升': [[22, 22]], '发': [[27, 27]], '影': [[41, 41]]}, 'company': {'的': [[7, 7]], '。': [[15, 15]], '流': [[24, 24]]}, 'government': {'率': [[8, 8]], '队': [[9, 9]], '加': [[12, 12]], '》': [[29, 29], [37, 37]], '辛': [[32, 32]], '普': [[33, 33]], '森': [[34, 34]], '家': [[36, 36]]}}}
> ```
> 
> 试了好几次都是这样 已经尝试过Albert, Roberta等

你好，请问这个问题是怎么解决的，我也遇到了，谢谢

**Comment by WillWillWong** [comment]
> > @rsanshierli 预测输出如下
> > ```shell
> > [Predicting] 10/10 [==============================] 16.0ms/step{'text': '四川敦煌学”。近年来，丹棱县等地一些不知名的石窟迎来了海内外的游客，他们随身携带着胡文和的著作。', 'label': {'movie': {'四': [[0, 0]]}, 'game': {'学': [[4, 4]]}, 'company': {'。': [[6, 6], [47, 47]], '年': [[8, 8]], '来': [[9, 9]], '，': [[10, 10], [33, 33]], '丹': [[11, 11]], '县': [[13, 13]], '地': [[15, 15]], '些': [[17, 17]], '名': [[20, 20]], '的': [[21, 21], [30, 30], [44, 44]], '了': [[26, 26]], '外': [[29, 29]], '客': [[32, 32]], '们': [[35, 35]], '身': [[37, 37]], '着': [[40, 40]]}, 'name': {'棱': [[12, 12]], '等': [[14, 14]], '他': [[34, 34]]}, 'government': {'知': [[19, 19]], '窟': [[23, 23]], '迎': [[24, 24]], '海': [[27, 27]], '著': [[45, 45]]}}}
> > {'text': '尼日利亚海军发言人当天在阿布贾向尼日利亚通讯社证实了这一消息。', 'label': {'position': {'军': [[5, 5]]}, 'government': {'发': [[6, 6]], '阿': [[12, 12]], '贾': [[14, 14]], '利': [[18, 18]], '亚': [[19, 19]], '通': [[20, 20]], '证': [[23, 23]], '息': [[29, 29]]}, 'company': {'当': [[9, 9]], '天': [[10, 10]], '向': [[15, 15]], '了': [[25, 25]]}}}
> > {'text': '销售冠军：辐射3-Bethesda', 'label': {'company': {'销': [[0, 0]], 'B': [[9, 9]], 'e': [[10, 10]], 'a': [[16, 16]]}, 'scene': {'售': [[1, 1]], '：': [[4, 4]], 't': [[11, 11]], 'e': [[13, 13]], 's': [[14, 14]]}, 'address': {'军': [[3, 3]]}, 'position': {'h': [[12, 12]]}}}
> > {'text': '所以大多数人都是从巴厘岛南部开始环岛之旅。', 'label': {'name': {'大': [[2, 2]], '从': [[8, 8]], '厘': [[10, 10]], '部': [[13, 13]]}, 'company': {'数': [[4, 4]], '人': [[5, 5]], '都': [[6, 6]], '是': [[7, 7]], '巴': [[9, 9]], '之': [[18, 18]], '旅': [[19, 19]]}}}
> > {'text': '备受瞩目的动作及冒险类大作《迷失》在其英文版上市之初就受到了全球玩家的大力追捧。', 'label': {'company': {'备': [[0, 0]], '受': [[1, 1]], '之': [[24, 24]], '初': [[25, 25]], '了': [[29, 29]], '家': [[33, 33]], '力': [[36, 36]], '捧': [[38, 38]]}, 'scene': {'瞩': [[2, 2]]}, 'government': {'险': [[9, 9]], '类': [[10, 10]]}, 'name': {'在': [[17, 17]], '大': [[35, 35]]}}}
> > {'text': 'filippagowski：14岁时我感觉自己像梵高', 'label': {'movie': {'f': [[0, 0]]}, 'company': {'i': [[12, 12]]}, 'government': {'像': [[23, 23]], '梵': [[24, 24]]}}}
> > {'text': '央视新址文化中心外立面受损严重', 'label': {'company': {'央': [[0, 0]], '新': [[2, 2]], '化': [[5, 5]], '重': [[14, 14]]}, 'name': {'视': [[1, 1]]}, 'government': {'中': [[6, 6]], '心': [[7, 7]]}}}
> > {'text': '单看这张彩票，税前总奖金为5063992元。本张票面缩水后阿森纳的结果全部为0，斯图加特全部为1，', 'label': {'name': {'看': [[1, 1]], '6': [[15, 15]]}, 'company': {'这': [[2, 2]], '票': [[5, 5], [24, 24]], '前': [[8, 8]], '金': [[11, 11]], '本': [[22, 22]], '面': [[25, 25]], '缩': [[26, 26]]}, 'government': {'彩': [[4, 4]], '奖': [[10, 10]], '水': [[27, 27]], '阿': [[29, 29]], '森': [[30, 30]], '纳': [[31, 31]], '果': [[34, 34]], '0': [[38, 38]], '斯': [[40, 40]], '图': [[41, 41]], '加': [[42, 42]], '特': [[43, 43]], '为': [[46, 46]]}, 'scene': {'为': [[12, 12]], '9': [[18, 18]], '2': [[19, 19]]}, 'game': {'1，': [[47, 48]]}}}
> > {'text': '你会和星级厨师一道先从巴塞罗那市中心兰布拉大道的laboqueria市场的开始挑选食材，', 'label': {'name': {'你': [[0, 0]], '级': [[4, 4]], '先': [[9, 9]], '从': [[10, 10]], '中': [[16, 16]], '心': [[17, 17]], '布': [[19, 19]]}, 'company': {'和': [[2, 2]]}, 'position': {'巴': [[11, 11]]}, 'scene': {'塞': [[12, 12]]}, 'government': {'大': [[21, 21]], '道': [[22, 22]], '市': [[34, 34]], '材': [[42, 42]]}}}
> > {'text': '波特与凤凰社》的率队下更加红火。乘着7月的上升气流，《发胶》、《辛普森一家》、《谍影憧憧ⅲ》', 'label': {'name': {'特': [[1, 1]]}, 'scene': {'凰': [[4, 4]], '》': [[6, 6], [45, 45]], '乘': [[16, 16]], '月': [[19, 19]], '升': [[22, 22]], '发': [[27, 27]], '影': [[41, 41]]}, 'company': {'的': [[7, 7]], '。': [[15, 15]], '流': [[24, 24]]}, 'government': {'率': [[8, 8]], '队': [[9, 9]], '加': [[12, 12]], '》': [[29, 29], [37, 37]], '辛': [[32, 32]], '普': [[33, 33]], '森': [[34, 34]], '家': [[36, 36]]}}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 试了好几次都是这样 已经尝试过Albert, Roberta等
> 
> 你好，请问这个问题是怎么解决的，我也遇到了，谢谢

你好。我进行了一系列调试，还是不好使？现在有解决结果了嘛
